---
# Page title
title: 指数
# summary
summary: 指数是测定多项内容数量综合变动的相对数。
# Date page published
date: 2022-8-5
lastmod: '2022-08-09T16:44:38+08:00'
# Book page type (do not modify).
type: book

# Position of this page in the menu. Remove this option to sort alphabetically.
weight: 11

toc: true
---


# 指数概念

指数是测定多项内容数量综合变动的相对数。

* 指数的实质是测定多项内容。比如零售价格指数反映的是零售市场几百万种商品价格变化的整体状况。
* 表现形式为动态相对数

# 指数分类

角度|分类1|分类2|比较
-|-|-|-
按照考察对象的范围|**个体指数**：反映总体中个别现象或个别项目数量变动的相对数|**总指数**：综合反映多种项目数量变动的相对数|总体商品包含很多个项目（商品1，商品2，……）。<br/>总指数在计算时，不是对个体指数的简单加和。因为不同个体之间的计量单位和价值可能存在差异。必须要利用**同度量因素**。比如不同个体之间的销售量和价格相加都是没有意义的，但是不同个体之间的销售额相加就是有意义的。所以我们可以找到这样的同度量因素，使个体之间可以相加。步骤为<br/>1. 确定同度量因素<br/>2. 确定同度量因素所在的时期<br/>3. 对比<br/>同度量因素就是使不同度量的现象可以过渡为同度量的媒介因素。而同时还起到“权数”的作用。
反映指标的性质|**数量指标指数**:反映数量指标变动程度的相对数,如商品销售量指数|**质量指标指数**:反映品质指标变动程度的相对数。如产品价格指数。|划分具有相对性。如单位产品原材料消耗量指标，相对于产品产量指标。它是质量指标；但相对于单位原材料价格指标，它又是数量指标。
计算形式|**简单指数**：记入指数的各个项目的重要性视为相同|**加权指数**：记入指数的各个项目依据重要程度赋予不同的权数<br/>加权指数分为两种，即综合形式和平均形式。<br/>采用综合形式编制的加权指数称为**加权综合指数**,<br/>采用平均形式编制的加权指数可称为**加权平均指数**|有权数和无权数的区别

# 指数编制中的问题

1. 选择项目
   * 在计算总指数时，不可能将所有的项目都纳入指数的计算中，被选中的项目成为“代表规格品”。
2. 确定权数
   * 一种是利用已有的信息构造权数
   * 一种是主观权数
3. 指数计算方法

# 总指数编制方法

计算数量指数时，权数（价格）应该定在基期

计算质量指数时：

* 基期：在基期商品结构下价格的整体变动
* 报告期：现实商品（产品）结构下价格的整体变动，商品结构变化的影响会融入价格指数，更能揭示价格变动的实际影响

加权平均指数主要用于价格指数的计算

加权综合指数主要用于数量指数的计算

加权平均指数给我们的启示是如果权数$\frac{qp}{\sum pq}$相对稳定，在计算指数时就不
必去搜集$\frac{q_0p_0}{\sum q_0p_0}$或$\frac{q_1p_1}{\sum p_1q_1}$，可以采用固定权数的方法

加权算术平均指数和加权调和平均指数没有什么区别，关键是权数$pq$的时期选择

[见表](../指数编制.html)

# 指标体系

一个总量往往可以分解成若干个因素，因数量关系可以用指标体系的形式表现出来。我们把
这种由总量指数及其若干个因素指数构成的数量关系式称为指数体系。

要求：

1. 
为使总量指数等于各因素指数的乘积，两个因素指数中通常一个为数量指数，一个是质量指数
2. 而且各因素指数中权数必须是不同时期的，比如数量指数用基期权数加权，质量指数则必须用报告期权数加权。

加权综合指数根据所选权数时期不同，可以形成不同的时期，但在实际中表格中的比较常用。

# 平均数变动因素分解

因素分解的思想同样可以用到平均数变动分析中。

在分组数据情况下，加权算术平均数的计算公式为：
$$\bar{x}=\frac{\sum xf}{\sum f}=\sum(x \frac{f}{\sum f})$$
由此可以看出，平均数的变动仍然受两个因素的影响:

* x:各组的变量水平，看做质量指标
* $\frac{f}{\sum f}$:各组的结构$\frac{f}{\sum f}$,看做数量指标

1. 总平均水平指数 $$I_{xf}=\frac{\bar{x}_1}{\bar{x}_0}=\frac{\sum x_1f_1/\sum f_1}{\sum x_0f_0/\sum f_0}$$

2. 组水平变动指数 $$I_x=\frac{\bar{x}_1}{\bar{x}_n}=\frac{\sum x_1f_1/\sum
   f_1}{\sum x_0f_1/\sum f_1}$$

3. 结构变动指数 $$I_f=\frac{\bar{x}_n}{\bar{x}_0}=\frac{\sum x_0f_1\sum
   f_1}{\sum x_0f_0\sum f_0}$$

此时：指数体系的具体表现形式为：

$总平均水平指数=组平均水平指数 \times 结构变动指数$

即$$\frac{\sum x_1f_1/\sum f_1}{\sum x_0f_0/\sum f_0}=\frac{\sum x_1f_1/\sum
   f_1}{\sum x_0f_1/\sum f_1} \times \frac{\sum x_0f_1\sum f_1}{\sum x_0f_0\sum
   f_0}$$

简写为:$I_{xf}=I_x\times I_f$

$总平均水平变动额=各组水平变动额+结构影响变动额$即$$\sum x_1f_1/\sum f_1-\sum x_0f_0/\sum f_0=(\sum x_1f_1/\sum
   f_1-\sum x_0f_1/\sum f_1)+(\sum x_0f_1\sum
   f_1-\sum x_0f_0\sum f_0)$$

简写为:$\bar{x}_1-\bar{x}_0=(\bar{x}_n-\bar{x_0})+(\bar{x}_1-\bar{x}_n)$

计算时，先计算基期，报告期，假定的平均变量水平$\bar{x}_0,\bar{x}_1,\bar{x}_n$。然后剩下的就跟因素分解差不多

# 几种典型的指数

指数|计算方法|介绍|应用
-|-|-|-
**居民消费价格指数**|$I_p=\frac{\sum iW}{\sum W}$|1. 选择代表规格品<br/>2. 选择调查市县<br/>3. 价格的调查与计算<br/>4. 权数的确定<br/>5. 指数计算（具体计算过程是，先分别计算出各代表规格品基期和报告期的全社会综合平均价，并计算出相应的价格指数，然后分层逐级计算小类、中类、大类和总指数。|除了能够反映城乡居民所购买的生活消费品和服务项目价格变动趋势和程度。<br/>1. 反映通货膨胀状况 $$通货膨胀率=\frac{报告期居民消费价格指数-基期居民消费价格指数}{基期居民消费价格指数}\times 100%$$ 2. 反映军民购买力水平 $$货币购买力指数=\frac{1}{居民消费价格指数}\times 100%$$ 3.测定职工实际工资水平。$$实际工资=\frac{名义工资}{居民消费价格指数}$$
股票价格指数|上证综合指数<br/>$$今日股价指数=\frac{今日市价总值}{基日市价总值}\times 100$$|市价总值等于收盘价乘以发行股数|(1)该指数能全面的，准确的反映某个时点股票价格的全面变动情况，考虑到行业分布和不同公司的规模，具有广泛的代表性。但是敏感性差。<br/>(2) 该指数以发行量为权数，好处是比较全面。
消费者满意度指数||计算各公司的消费者满意度指数后，需要确定上一层次（行业）指数计算的权重，进而计算经济领域指数和全国指数。在计算行业指数时，以各公司销售份额的比重作为权数；计算经济领域指数时，以各行业销售份额的比重作为权数；计算全国指数时，以各经济领域GDP的贡献百分比作为权数|

## 零售价格总指数计算的例子

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
showProcessingMessages: false, //关闭js加载过程信息
messageStyle: "none", //不显示信息
extensions: ["tex2jax.js"],
jax: ["input/TeX", "output/HTML-CSS"],
tex2jax: {
inlineMath: [ ['$','$'], ["\\(","\\)"] ],
displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
skipTags: ['script', 'noscript', 'style', 'textarea', 'pre','code', 'a', 'annotation', 'annotation-xml'],
ignoreClass: 'crayon-.*' // 'crayon-' 开头的类，属于Wordpress代码高亮库，这部分不需要处理，否则会导致显示不正确,这部分是正则式，多条之间用'|'分割    
},
'HTML-CSS': {
showMathMenu: false //禁用右键菜单
}
});
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML-full"></script>

<table>
<tr>
<th rowspan="2">商品类别及名称</th>
<th colspan="2">平均价格</th>
<th rowspan="2">权数W</th>
<th rowspan="2">价格指数</th>
<th rowspan="2">小类指数</th>
<th rowspan="2">中类指数</th>
<th rowspan="2">大类指数</th>
<th rowspan="2">指数i(%)</th>
</tr>
<tr>
<th>$p_0$</th>
<th>$p_1$</th>
</tr>
<tr>
<td >总指数</td>
<td colspan="2"></td>
<td colspan="1">100</td>
<td colspan="5">$I_p=\frac{38\times 116.2+62 \times 100.3}{100}=106.34\%$</td>

</tr>
<tr>
<td>一：食品类</td>
<td></td>
<td></td>
<td>38</td>
<td></td>
<td></td>
<td></td>
<td>$i_p=\frac{105.35\times 35+125.4\times 45+114.8\times 20}{100}=116.2\%$</td>
<td>116.2</td>
</tr>
<tr>
<td>1.粮食</td>
<td></td>
<td></td>
<td>35</td>
<td></td>
<td></td>
<td>$\frac{105.6\times 65+104.8\times 35}{100}=105.3\%$</td>
<td></td>
<td>105.3</td>
</tr>
<tr>
<td>细粮</td>
<td></td>
<td></td>
<td>65</td>
<td></td>
<td>$\frac{105\times 40+106\times 60}{100}=105.6\%$</td>
<td></td>
<td></td>
<td>105.6</td>
</tr>
<tr>
<td>面粉</td>
<td>2.40</td>
<td>2.52</td>
<td>40</td>
<td>$\frac{2.52}{2.40}=105.0\%$</td>
<td></td>
<td></td>
<td></td>
<td>105.0</td>
</tr>
<tr>
<td>大米</td>
<td>3.50</td>
<td>3.71</td>
<td>60</td>
<td>$\frac{3.71}{3.50}=106.0\%$</td>
<td></td>
<td></td>
<td></td>
<td>106.0</td>
</tr>
<tr>
<td>粗粮</td>
<td></td>
<td></td>
<td>35</td>
<td></td>
<td>104.8%</td>
<td></td>
<td></td>
<td>104.8</td>
</tr>
<tr>
<td>2.副食品</td>
<td></td>
<td></td>
<td>45</td>
<td></td>
<td></td>
<td>125.4%</td>
<td></td>
<td>125.4</td>
</tr>
<tr>
<td>3.其他食品</td>
<td></td>
<td></td>
<td>20</td>
<td></td>
<td></td>
<td>114.8%</td>
<td></td>
<td>114.8</td>
</tr>
<tr>
<td>其他</td>
<td></td>
<td></td>
<td>62</td>
<td></td>
<td></td>
<td></td>
<td>100.3%</td>
<td>100.3</td>
</tr>
</table>

# 综合评价指数

统计的综合评价是针对研究的对象，建立一个进行测评的指标体系，利用一定的方法或模型，对搜集的资料进行分析，对被评价的事物做出量化的总体判断。

综合评价指数时将评价结果数量化的一种技术处理，它将多指标进行综合，最后形成概括性的一个指数，通过指数比较达到评价的目的。

综合评价指数的基础是单项指标，由于不同的单项指标通常不能直接进行加减乘除的运算，需要将数据处理技术与指数分析方法结合起来。

构建综合评价指数

1. 建立综合评价指标体系
2. 评价指标的无量纲化处理
   
   无量纲化的处理方法:

   1. 统计标准化:$z_i=\frac{x_i-\bar{x}}{s},z_i为第i个指标的标准化值；\bar{x}为x_i的均值；s为标准差$
   2. 相对标准化:先给一个评价指标确定一个标准值，然后用实际值和标准值进行比较，实现指标的相对化处理。<br/>$x_i=\frac{x_i}{x_s}$,$x_s$为进行标准化确定的对比标准，通常可以选择最优值或平均值作为对比标准。
   3. 功效系数法:$z_i=\frac{x_i-min(x_i)}{max(x_i)-min(x_i)}$，取值为0到1之间<br/>改进的功效系数法:$z_i=\frac{x_i-min(x_i)}{max(x_1)-min(x_i)}\times 40+60$,这样得到的标准化分数在$60到100$之间。<br/>然后结合各指标的权重，就可以计算综合评价指数。通常采用加权平均方式进行处理，公式为$I=\frac{\sum _{i=1}^nz_iw_i}{\sum_{i=1}^nw_i}$,式中，$0\leq w_i \leq 1,\sum_{i=1}^nw_i=1$
3. 确定各项评价指标的权重
4. 计算综合评价指数


















